src/django_app/course_navi/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('course_navi.views',
    url(r'^$', 'index', name='index'),
    url(r'^timetable$', 'timetable', name='timetable'),
    url(r'^message$', 'message', name='message'),
    url(r'^news$', 'news', name='news'),
    url(r'^settings$', 'settings', name='settings'),
    url(r'^class$', 'lecture', name='lecture')
)

src/django_app/net_portal/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'portal.views.index', name='index'),
    url(r'^', include('students.urls', namespace='students', app_name='students')),
    url(r'^cnavi/', include('course_navi.urls', namespace='cnavi', app_name='cnavi')),
    url(r'^about$', 'portal.views.about', name='about'),
    url(r'^team$', 'portal.views.team', name='team'),
    url(r'^contact$', 'portal.views.contact', name='contact')
)

src/django_app/students/urls.py
from django.conf.urls import patterns, url, include
from students.views import *


registration_patterns = patterns('',
    url(r'^registration/update$', update, name='registration_update')
)

session_patterns = patterns('',
    url(r'^login$', login, name='login'),
    url(r'^make_login$', make_login, name='make_login'),
    url(r'^logout$', logout, name='logout')
)

urlpatterns = patterns('students.views',
    url(r'^cnavi/', include(registration_patterns)),
    url(r'^', include(session_patterns))
)

src/django_app/course_navi/models.py
from django.db import models

# Create your models here.

src/django_app/course_navi/views.py
from django.template import loader, Context
from django.http import HttpResponse
from django.shortcuts import render
from courses.models import Period
from extended_models.models import SerializableList

def index(request):
    registrations = request.user.get_profile().get_subjects()
    periods = SerializableList(Period.objects.all())
    return render(request, "course_navi/index.html", {
            'user': request.user,
            'registrations': registrations,
            'periods': periods,
            'unread_messages': 20
        })

def timetable(request):
    t = loader.get_template("course_navi/timetable.html")
    return HttpResponse(t.render(Context({})))

def message(request):
    t = loader.get_template("course_navi/message.html")
    return HttpResponse(t.render(Context({})))

def news(request):
    t = loader.get_template("course_navi/news.html")
    return HttpResponse(t.render(Context({})))

def settings(request):
    t = loader.get_template("course_navi/settings.html")
    return HttpResponse(t.render(Context({})))

def lecture(request):
    t = loader.get_template("course_navi/lecture.html")
    return HttpResponse(t.render(Context({})))

src/django_app/templates/course_navi/bases/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>CourseN@vi 2.0</title>
    <link rel="shortcut icon" href="/static/images/favicon.ico" />
    <link href="/static/stylesheets/screen.css" media="all" rel="stylesheet" type="text/css">
    <!--
    <script src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.1/require.min.js"></script> -->

    <!-- use local lib for dev to be able to develop offline (in the metro ;o) -->
    <script src="/static/js/lib/requirejs/require.js"></script>
    <script>
        define('common/bootstrap', function() {
            return {
                registrations: {{registrations.to_json|safe}}
              , user: {{user.get_profile.to_json|safe}}
              , periods: {{periods.to_json|safe}}
            };
        });
    </script>
    <script src="/static/js/cnavi/main.js"></script>
</head>
<body>
    <div id="header">
        <a href="{% url 'cnavi:index' %}">
            <div class="logo"><div class="icons-logo sprite"></div></div>
        </a>
        <!--div class="menu">
            <ul>
                <a href="#"><li class="active"><img src="images/coursenavi_icon.png" width="30" />Course N@vi</li></a>
                <a href="#"><li class="">Course N@vi</li></a>
            </ul>
        </div-->
<!--         <div class="logout">
            <span class="greeting">
                {% blocktrans with name=user.get_profile.jp_first_name %}hello {{name}}{% endblocktrans %}
            </span>
            <span>
                <a href="{% url 'students:logout' %}">
                    <div class="icons-logout sprite"></div>
                    {% trans "logout" %}
                </a>
            </span>
        </div> -->
    </div>
    <div id="content-wrapper">
        <div id="sidebar">
            <div class="sidebar">
                {% block sidebar %}{% endblock %}
            </div>
            <div class="footer">

            </div>
        </div>
        <div id="main">
            <div class="header">
                {% block main_header %}{% endblock %}
            </div>
            <div class="body {% block name %}{% endblock %}">
                {% block main_body %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>