src/django_app/course_navi/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('course_navi.views',
    url(r'^$', 'index', name='index'),
    url(r'^timetable$', 'timetable', name='timetable'),
    url(r'^message$', 'message', name='message'),
    url(r'^news$', 'news', name='news'),
    url(r'^settings$', 'settings', name='settings'),
    url(r'^class$', 'lecture', name='lecture')
)

src/django_app/net_portal/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'portal.views.index', name='index'),
    url(r'^', include('students.urls', namespace='students', app_name='students')),
    url(r'^cnavi/', include('course_navi.urls', namespace='cnavi', app_name='cnavi')),
    url(r'^about$', 'portal.views.about', name='about'),
    url(r'^team$', 'portal.views.team', name='team'),
    url(r'^contact$', 'portal.views.contact', name='contact')
)

src/django_app/students/urls.py
from django.conf.urls import patterns, url, include
from students.views import *


registration_patterns = patterns('',
    url(r'^registration/update$', update, name='registration_update')
)

session_patterns = patterns('',
    url(r'^login$', login, name='login'),
    url(r'^make_login$', make_login, name='make_login'),
    url(r'^logout$', logout, name='logout')
)

urlpatterns = patterns('students.views',
    url(r'^cnavi/', include(registration_patterns)),
    url(r'^', include(session_patterns))
)

src/django_app/course_navi/models.py
from django.db import models

# Create your models here.

src/django_app/course_navi/views.py
from django.template import loader, Context
from django.http import HttpResponse
from django.shortcuts import render
from courses.models import Period
from extended_models.models import SerializableList

def index(request):
    registrations = request.user.get_profile().get_subjects()
    periods = SerializableList(Period.objects.all())
    return render(request, "course_navi/index.html", {
            'user': request.user,
            'registrations': registrations,
            'periods': periods,
            'unread_messages': 20
        })

def timetable(request):
    t = loader.get_template("course_navi/timetable.html")
    return HttpResponse(t.render(Context({})))

def message(request):
    t = loader.get_template("course_navi/message.html")
    return HttpResponse(t.render(Context({})))

def news(request):
    t = loader.get_template("course_navi/news.html")
    return HttpResponse(t.render(Context({})))

def settings(request):
    t = loader.get_template("course_navi/settings.html")
    return HttpResponse(t.render(Context({})))

def lecture(request):
    t = loader.get_template("course_navi/lecture.html")
    return HttpResponse(t.render(Context({})))

src/django_app/templates/course_navi/subtemplates/sidebar_course_navi.html
<ul>
	<a href="#">
        <li class="{{ home }}">
            <div class="home sprite"></div>ホーム
        </li>
    </a>
    <a href="#timetable">
        <li class="{{ timetable }}">
            <div class="timetable sprite"></div>時間割
        </li>
    </a>
    <a href="{% url 'cnavi:message' %}">
        <li class="{{ message }}">
            <div class="message sprite"></div>メッセージ
		{% if unread_messages %}
			<span class="indicator">{{ unread_messages }}</span>
		{% endif %}
	    </li>
    </a>
	<a href="{% url 'cnavi:news' %}">
        <li class="{{ news }}">
            <div class="news sprite"></div>お知らせ
        </li>
    </a>
	<a href="{% url 'cnavi:settings' %}">
        <li class="{{ settings }}">
            <div class="gear sprite"></div>設定
        </li>
    </a>
</ul>